// src/App.svelte
<script lang="ts">
    import Display from "./components/Display.svelte";
    import Keypad from "./components/Keypad.svelte";
    import {makeGame} from "./stores/game";

    const game = makeGame()
</script>

<Display value={$game.value} score={$game.score} hasError={$game.hasError}/>
<Keypad onClick={v => $game.answer(v)}/>

// src/app/page.tsx
"use client";

import Display from "@/components/Display";
import Keypad from "@/components/Keypad";
import {useCallback} from "react";

export default function Home() {
  const onInput = useCallback((v: number) => {
    console.log("Button pressed:", v)
  }, [])

  return (
    <main className="container">
      <Display value={"56 : ? = 7"} score={50} hasError={false}/>
      <Keypad onClick={onInput}/>
    </main>
  );
}
