// src/components/Keypad.tsx
import style from './Keypad.module.css'
import Button from "./Button";

interface Props {
    onClick: (v:number) => void
}

export default function Keypad(props: Props) {
    return <div className={style.container}>
        <div className={style.row}>
            <Button onClick={props.onClick} value={1}/>
            <Button onClick={props.onClick} value={2}/>
            <Button onClick={props.onClick} value={3}/>
        </div>
        <div className={style.row}>
            <Button onClick={props.onClick} value={4}/>
            <Button onClick={props.onClick} value={5}/>
            <Button onClick={props.onClick} value={6}/>
        </div>
        <div className={style.row}>
            <Button onClick={props.onClick} value={7}/>
            <Button onClick={props.onClick} value={8}/>
            <Button onClick={props.onClick} value={9}/>
        </div>
    </div>
}

// src/components/Keypad.svelte
<script lang="ts">
    import Button from "./Button.svelte";

    export let onClick: (v: number) => void
</script>

<div class="keypad">
    <div class="keypad-row">
        <Button value={1} onClick={onClick}/>
        <Button value={2} onClick={onClick}/>
        <Button value={3} onClick={onClick}/>
    </div>
    <div class="keypad-row">
        <Button value={4} onClick={onClick}/>
        <Button value={5} onClick={onClick}/>
        <Button value={6} onClick={onClick}/>
    </div>
    <div class="keypad-row">
        <Button value={7} onClick={onClick}/>
        <Button value={8} onClick={onClick}/>
        <Button value={9} onClick={onClick}/>
    </div>
</div>

<style>
    .keypad {
        display: block;
        padding: calc(1.5 * var(--vw));
    }

    .keypad-row {
        display: flex;
        width: 100%;
    }
</style>
