// src/App.svelte
<script lang="ts">
    import {onMount} from "svelte";
    import {Game} from "./lib/game";
    import Display from "./components/Display.svelte";
    import Keypad from "./components/Keypad.svelte";

    const game = new Game()
    let display: Display

    onMount(() => {
        game.onError = display.notifyError
        update()
    })

    function update() {
        game.tick()
        requestAnimationFrame(update)
    }
</script>

<Display bind:this={display} score={$game.score} value={$game.value}/>
<Keypad onClick={v => game.tryAnswer(v)}/>

// src/app.tsx
import Keypad from "./components/Keypad.tsx";
import Display from "./components/Display.tsx";
import {Game} from "./core/game.ts";
import {createSignal, onMount} from "solid-js";

import type {JSXElement} from "solid-js";

export default function App(): JSXElement {
    const [track, update] = createSignal(null, {equals: false} )

    const game = new Game()
    const value = () => {track(); return game.value.toString()}
    const score = () => {track(); return game.score}
    const hasError = () => {track(); return game.hasError}

    onMount(() => {
        function tick() {
            game.update()
            update(null)
            requestAnimationFrame(tick)
        }
        requestAnimationFrame(tick)
    })

    return (
        <>
            <Display value={value()} score={score()} hasError={hasError()}/>
            <Keypad onClick={v => {
                game.answer(v)
                update(null)
            }}/>
        </>
    )
}
